In [5]:
import pandas as pd
import numpy as np
import os

os.chdir(r'C:\Programming\Github\EGCN\data')
os.getcwd()

'C:\\Programming\\Github\\EGCN\\data'

In [6]:
df = pd.read_csv('lipo.csv')
df

                                                 smiles  lipo
0               Cn1c(CN2CCN(CC2)c3ccc(Cl)cc3)nc4ccccc14  3.54
1     COc1cc(OC)c(cc1NC(=O)CSCC(=O)O)S(=O)(=O)N2C(C)... -1.18
2                COC(=O)[C@@H](N1CCc2sccc2C1)c3ccccc3Cl  3.69
3     OC[C@H](O)CN1C(=O)C(Cc2ccccc12)NC(=O)c3cc4cc(C...  3.37
4     Cc1cccc(C[C@H](NC(=O)c2cc(nn2C)C(C)(C)C)C(=O)N...  3.10
...                                                 ...   ...
4195            OCCc1ccc(NC(=O)c2cc3cc(Cl)ccc3[nH]2)cc1  3.85
4196  CCN(C1CCN(CCC(c2ccc(F)cc2)c3ccc(F)cc3)CC1)C(=O...  3.21
4197                                 COc1cccc2[nH]ncc12  2.10
4198                    Clc1ccc2ncccc2c1C(=O)NCC3CCCCC3  2.65
4199                 CN1C(=O)C=C(CCc2ccc3ccccc3c2)N=C1N  2.70

[4200 rows x 2 columns]

In [7]:
# 2000개 행만 랜덤 추출
df_reduced = df.iloc[np.random.randint(0, len(df), 2000)].reset_index(drop=True)
df_reduced

                                                 smiles  lipo
0       NC(=O)c1cnc(N[C@H]2CCCNC2)c3cc(sc13)c4ccc(F)cc4  2.01
1     CC(=O)N1CCN(CC1)c2ccc(NC(=O)c3oc(Nc4ccccc4F)nn...  2.51
2                     Cc1cc(C)c2c(N)c(sc2n1)C(=O)NC3CC3  2.53
3                          CCOC(=O)C1=Cc2ccc(O)cc2OC1=O  1.20
4     Cc1cc(CN2Cc3ccccc3C[C@H]2C(=O)Nc4ccc(Cl)cc4Cl)...  2.41
...                                                 ...   ...
1995          CCC[C@H](CO)Nc1nc(SCc2ccccc2)nc3nc(N)sc13  3.80
1996  COC[C@H](C)Oc1cc(Oc2ccc(Cl)cc2)cc(c1)C(=O)Nc3c...  1.69
1997  Clc1c(NCC2CCNCC2)nccc1C(=O)NCC34CC5CC(CC(C5)C3)C4  0.60
1998  Cn1cc(cc1c2c3C(=O)N(CC=C)C(=O)N(CC4CC4)c3nn2Cc...  4.27
1999  Cc1ccccc1N2C(=Nc3cccc(C)c3C2=O)Cn4nc(c5ccc(O)c...  3.55

[2000 rows x 2 columns]

In [8]:
# 저장
df_reduced.to_csv('lipo_reduced.csv', index = False)